[package]
name = "rust"
version = "0.1.0"
authors = ["masahiko-ofgp <ichigyo.zanmai@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["image"]
